### ISSUE TITLE
(IMPORT FAILED):  ComfyUI\custom_nodes\efficiency-nodes-comfyui

### ISSUE THREAD

**Issue by Piscabo** [jags111/efficiency-nodes-comfyui#149]
After todays update ### ComfyUI Revision: 2111 [38ed2da2] | Released on '2024-04-05'

Cannot import H:\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (H:\ComfyUI\comfy\samplers.py)

**Comment by jags111** [comment]
i am on it

**Comment by alenknight** [comment]
aw man. me too. ugh I knew I should have waited. haha

**Comment by jags111** [comment]
please check and update if nay issues. Thanks for your support

**Comment by alenknight** [comment]
yep! all fixed!  thanks!

**Comment by darkpixel** [comment]
Doesn't appear to be fixed:

```
Traceback (most recent call last):
  File "/ai/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/ai/ComfyUI/comfy/samplers.py)

Cannot import /ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/ai/ComfyUI/comfy/samplers.py)
```

**Comment by Feiyang12345** [comment]
我发现当版本切换到4.2日将不再显示报错，如果日期是4.4或者4.5报错又会显示出来。通过版本回退到4.2日可以临时解决这个问题。

**Comment by jags111** [comment]
okay will check again if any issues and updates as change is so frequent

**Comment by Fillllllllllll** [comment]
Same.. nomatter what i do.. i reinstalled comfy already - but still
Need help, please

**Comment by jags111** [comment]
all updates done and if any new issue raise a new one with workflow share! important i need the actual workflow to check what is wrong
