### ISSUE TITLE
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

### ISSUE THREAD

**Issue by Gileanxxx** [jags111/efficiency-nodes-comfyui#153]
Prompt executed in 0.24 seconds
Traceback (most recent call last):
  File "D:\comfyui\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 713, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 647, in process_latent_image
    samples = TSampler().sample(model, tile_seed, tile_size, tile_size, tiling_strategy, tiling_steps, cfg,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 314, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 123, in sample_common
    positive_copy = comfy.sample.convert_cond(positive)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/163095612/a83067cc-b782-4d6f-982f-72bac344400b)

I'm getting an error using Tiled Upscaler Script, can you help me?

**Comment by jags111** [comment]
Hai i need to test it now and get back to you on same and if any code issues will check and update

**Comment by jifee8505** [comment]
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/sampler_helpers.py#L20

**Comment by jifee8505** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/57753c964affd18d2b87d2a47fe6b375bca39004

**Comment by jags111** [comment]
okay will review this and update

**Comment by OtakuFra** [comment]
Hello, i get the same error, what can i do to fix this please. Thx for your work guys, it's fully appreciated

**Comment by caciottone** [comment]
Hello, i have same error.
