### ISSUE TITLE
installed failed

### ISSUE THREAD

**Issue by TigoTin** [jags111/efficiency-nodes-comfyui#165]
ubuntu20.04
python3.10
RTX4090

err msg:

Traceback (most recent call last):
  File "/root/tmp-disk/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (/root/tmp-disk/ComfyUI/comfy/samplers.py)

Cannot import /root/tmp-disk/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (/root/tmp-disk/ComfyUI/comfy/samplers.py)

**Comment by seannet888** [comment]
same question,follow+

**Comment by jags111** [comment]
can you try install using Manager and if so copy me the log so can check what is the issue

**Comment by badayvedat** [comment]
ComfyUI removed `wrap_model` function in commit https://github.com/comfyanonymous/ComfyUI/commit/57753c964affd18d2b87d2a47fe6b375bca39004 . That's why it can't find the `wrap_model` function.
