### ISSUE TITLE
Seems cannot work with SD3

### ISSUE THREAD

**Issue by jinxishe** [jags111/efficiency-nodes-comfyui#201]
Seems cannot work with SD3.
Maybe the checkpoint loader problem.

**Comment by jags111** [comment]
can you show where the problem occurred or any way to know how you connected

**Comment by WhatsCS** [comment]
Hijacking to provide more information on SD3 issues I'm facing:
Using the sd3_medium_incl_clips model I see the following exception:
```
Requested to load SD3ClipModel_
Loading 1 new model
!!! Exception during processing!!! 'g'
Traceback (most recent call last):
  File "/home/evalcode/Projects/ML/SD/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 179, in efficientloader
    encode_prompts(positive, negative, token_normalization, weight_interpretation, clip, clip_skip,
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 80, in encode_prompts
    positive_encoded = bnk_adv_encode.AdvancedCLIPTextEncode().encode(clip, positive_prompt, token_normalization, weight_interpretation)[0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_adv_encode.py", line 312, in encode
    embeddings_final, pooled = advanced_encode(clip, text, token_normalization, weight_interpretation, w_max=1.0,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_adv_encode.py", line 262, in advanced_encode
    return advanced_encode_from_tokens(tokenized['l'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_adv_encode.py", line 183, in advanced_encode_from_tokens
    weighted_emb, pooled_base = encode_func(weighted_tokens)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_adv_encode.py", line 265, in <lambda>
    lambda x: (clip.encode_from_tokens({'l': x}), None),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/comfy/sd.py", line 143, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/evalcode/Projects/ML/SD/ComfyUI/comfy/sd3_clip.py", line 96, in encode_token_weights
    token_weight_pairs_g = token_weight_pairs["g"]
                           ~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'g'
```
![workflow (1)](https://github.com/jags111/efficiency-nodes-comfyui/assets/4131740/fc2d65f2-5599-4dfa-9ba7-d2b977dd50c3)
basic workflow leveraging the example prompts and model sampling node from the stablility huggingface repo. Not really sure if the model sampling node is required but w/e.

**Comment by jags111** [comment]
Hai.. I checked .. it is the problem with clip for SD# 3 which needs additional nodes. Here is the testing reesults.
<img width="939" alt="2024-06-18_12-37-09" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/94921628-a81e-4057-afcc-df2d20b5e945">

<img width="1044" alt="2024-06-18_12-38-30" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/b2500535-50f4-4f42-a59a-98403412b549">
 Can you instead of using the eff loader or modify same to use. as native loader will not load SD 3 clip models as of now.

**Comment by jags111** [comment]
I think i need to revise this node to handle SD3 and Flux models

**Comment by Ainaemaet** [comment]
> I think i need to revise this node to handle SD3 and Flux models

@jags111 Has anything more been done for flux support??  Thank you kindly for the nodes, they are amazing - but I almost exclusively use FLUX now - and I think that will be very common for many people as we go forwards. 

It's been 3 months since you last commented about adding flux support, can we please get an update on this? 

Thank you!
