### ISSUE TITLE
AttributeError: module 'comfy.sample' has no attribute 'prepare_mask'

### ISSUE THREAD

**Issue by RGX650** [jags111/efficiency-nodes-comfyui#223]
Tiled Upscaler Script + Conditioning (Set Mask)

should it rather be instaed:           comfy.sampler_helpers.prepare_mask

!!! Exception during processing!!! module 'comfy.sample' has no attribute 'prepare_mask'
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\COMFYUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\COMFYUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 732, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 664, in process_latent_image
    samples = TSampler().sample(model, tile_seed, tile_size, tile_size, tiling_strategy, tiling_steps, cfg,
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 325, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 170, in sample_common
    spatial_conds_pos = [
  File "C:\AI\COMFYUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 172, in <listcomp>
    comfy.sample.prepare_mask(c[1]['mask'], shape, device) if 'mask' in c[1] else None)
AttributeError: module 'comfy.sample' has no attribute 'prepare_mask'

**Comment by jags111** [comment]
need to check if this is coming from any new updates
