### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fresno808** [jags111/efficiency-nodes-comfyui#225]
No matter how many times Ive tried installing and reinstalling, either through manager or git pull, I get an import error. Any ideas on how to fix it?

**Comment by jags111** [comment]
strange and not having a clear idea on it. can you post the log details

**Comment by fresno808** [comment]
Cannot import C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: expected np.ndarray (got numpy.ndarray)
Traceback (most recent call last):
  File "C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\djtid\\OneDrive\\Documents\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\pfg-ComfyUI\\__init__.py'

**Comment by jags111** [comment]
can you check the specific node pfg-ComfyUI which is having an issue and you need to resolve it. it is coming from there. May be the repo needs reinstall or install from comfy-Manager.

**Comment by fresno808** [comment]
hello, the efficiency seems to work when i dont have comfyui manager installed, but then when i install manager it messes up the efficiency node.
