### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by wj123-wj** [jags111/efficiency-nodes-comfyui#249]
Author, I am having problems installing this plugin，Could you please help me，This is an error code
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main\efficiency_nodes.py", line 403, in <module>
    class TSC_KSampler:
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main\efficiency_nodes.py", line 404, in TSC_KSampler
    empty_image = pil2tensor(Image.new('RGBA', (1, 1), (0, 0, 0, 0)))
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main\tsc_utils.py", line 83, in pil2tensor
    return torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0)
TypeError: expected np.ndarray (got numpy.ndarray)

Cannot import D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main module for custom nodes: expected np.ndarray (got numpy.ndarray)
Patching UNetModel.forward

**Comment by jags111** [comment]
Hai. I don't have this file --efficiency-nodes-comfyui-main_init.py .. so check which one is throwing this error. It is caused by numpy and you have a version mismatch.

**Comment by michaeisz** [comment]
Author, I am also having problems installing this plugin，Could you please help me，This is an error code
Traceback (most recent call last):
 File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                               
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                          
  File "C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>                                                                                         
    from .efficiency_nodes import NODE_CLASS_MAPPINGS                                                                   
  File "C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>                                                                                
    from .py import smZ_cfg_denoiser                                                                                    
  File "C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>                                                                              
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint                                            
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)

Cannot import C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (C:\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py) 

thank you very much!
