### ISSUE TITLE
Connecting any LoRA Stack to Efficient Loader results in "TypeError: unhashable type: 'list'" on second queue

### ISSUE THREAD

**Issue by darkpixel** [jags111/efficiency-nodes-comfyui#256]
It doesn't seem to matter what LoRA Stacker you connect to Efficient Loader.
On the first queue, everything works perfectly.
On the second queue, it crashes:
```
got prompt
!!! Exception during processing !!! unhashable type: 'list'
Traceback (most recent call last):
  File "/ai/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ai/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 158, in efficientloader
    model, clip = load_lora(lora_params, ckpt_name, my_unique_id, cache=lora_cache, ckpt_cache=ckpt_cache, cache_overwrite=True)
  File "/ai/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 329, in load_lora
    if set(entry[0]) == set(lora_params) and entry[1] == ckpt_name:
TypeError: unhashable type: 'list'

Prompt executed in 0.03 seconds
```

**Comment by darkpixel** [comment]
If I ```CTRL+C``` to kill Comfy and then start it up again, all I have to do is hit the "Queue" button and it succeeds again, then fails the second time.
