### ISSUE TITLE
Error using KSampler (Efficient) after ComfyUI update

### ISSUE THREAD

**Issue by comfyhelper1** [jags111/efficiency-nodes-comfyui#32]
Windows 11
Updated ComfyUI - 11/16/2023
Deleted Old efficiency-nodes-comfyui and re-insalled this version - 11/16/2023
Nvidia 3090

I dragged this image into my ComfyUI and adjusted the lora, checkpoints, and made the seeds random. I get the below error and am unsure how to proceed. Do you need more information or should I try any steps before re-installing ComfyUI?

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/151058950/b1aebd55-3c65-46af-9ba0-c0e059730df3)

`ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 1542, in sample
    process_values(model, refiner_model, add_noise, seed, steps, start_at_step, end_at_step,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 1413, in process_values
    samples, images, _, _ = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 533, in process_latent_image
    samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1237, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1207, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 98, in sample
    sampler = comfy.samplers.KSampler(real_model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 321, in __init__
    set_model_k(self)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 308, in set_model_k
    self.model_denoise = CFGNoisePredictor(self.model) # main change
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 256, in __init__
    self.inner_model2.num_timesteps = model.num_timesteps
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BaseModel' object has no attribute 'num_timesteps'`

**Comment by comfyhelper1** [comment]
Narrowing it now, it appears to occur when the Noise Control Script is added to the flow.
