### ISSUE TITLE
Batch of images to Image Overlay fails

### ISSUE THREAD

**Issue by JoeGay777** [jags111/efficiency-nodes-comfyui#66]
If I send a batch of images as the overlay_image input of the Image Overlay node I get this error:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 281, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 3887, in apply_overlay_image
    overlay_image = tensor2pil(overlay_image)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 79, in tensor2pil
    return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\AI Generators\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 281, 3), |u1

I've included a file that can be used to reproduce the failure.

[Error.json](https://github.com/jags111/efficiency-nodes-comfyui/files/13780624/Error.json)

**Comment by jags111** [comment]
let me review and update

**Comment by JoeGay777** [comment]
Thank you.

**Comment by jags111** [comment]
This error is caused by a strange node you added. I removed same and it is working perfect. see example below for it. you cant plugin any node unless it is perfect to the system. secondly always overlay node needs a PNG with alpha so it can remove the background and add to the same.

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/ad482e76-ebfc-4c1f-bf1e-8299a412fb17)

**Comment by JoeGay777** [comment]
OK.  Thank you.  I was trying to batch images into the overlay node so I could process different images without having to do them one at a time.
