### ISSUE TITLE
How to batch process in Image Overlay?

### ISSUE THREAD

**Issue by cheezecrisp** [jags111/efficiency-nodes-comfyui#86]
When processing single base_image and overlay_image, it's OK.
When processing batch base_images and single overlay_image, it's OK too.
BUT when processing single base_image and batch overlay_images, error occurs:

ERROR:root:Traceback (most recent call last):

File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 512, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 3887, in apply_overlay_image
    overlay_image = tensor2pil(overlay_image)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 79, in tensor2pil
    return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 512, 3), |u1


So, how to batch process overlay_images?

**Comment by jags111** [comment]
Hai. thanks . is it possible to share your workflow to understand what is happening under the hood. as the node was designed with single placement as each one needs values to be tweaked. Possibly something is missing in your workflow and may be bridged.

**Comment by cheezecrisp** [comment]
[ImageOverlay cases.json](https://github.com/jags111/efficiency-nodes-comfyui/files/13972112/ImageOverlay.cases.json)
Thanks for your help, I listed 3 cases of batch overlay_image for your reference, all of them pop errors

**Comment by jags111** [comment]
Hai here is an answer and before doing some thing like this please check workflows on same.
[ImageOverlayanswers.json](https://github.com/jags111/efficiency-nodes-comfyui/files/13992149/ImageOverlayanswers.json)
<img width="994" alt="2024-01-19_22-39-50" src="https://github.com/jags111/efficiency-nodes-comfyui
<img width="768" alt="2024-01-19_22-39-26" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/cf07e235-410b-405f-9f27-2f9a35e2816f">
/assets/5968619/bde74c0a-0a46-4e8f-86fc-c02168b0195f">
<img width="412" alt="2024-01-19_22-39-03" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/c1a68195-1ad4-4025-a38e-36e41deba0e6">

**Comment by cheezecrisp** [comment]
> Hai here is an answer and before doing some thing like this please check workflows on same. [ImageOverlayanswers.json](https://github.com/jags111/efficiency-nodes-comfyui/files/13992149/ImageOverlayanswers.json) <img alt="2024-01-19_22-39-50" width="994" src="https://private-user-images.githubusercontent.com/5968619/298144761-bde74c0a-0a46-4e8f-86fc-c02168b0195f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTYzNzQsIm5iZiI6MTcwNTcxNjA3NCwicGF0aCI6Ii81OTY4NjE5LzI5ODE0NDc2MS1iZGU3NGMwYS0wYTQ2LTRlOGYtODZmYy1jMDIxNjhiMDE5NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDIwMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2MTUxYWI5OGJhNjM1MWI4NjQyOGRiMWMzYmExNjBjODZmOTFiOTEzZmQ4YTk5M2JkNDZjZTdhZjU5MmIxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Iiycsfr-e15d5K8eOR3GQbL2gOSwGszzUtOkIpzdCxY">
> 
> <img alt="2024-01-19_22-39-26" width="768" src="https://private-user-images.githubusercontent.com/5968619/298144803-cf07e235-410b-405f-9f27-2f9a35e2816f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTYzNzQsIm5iZiI6MTcwNTcxNjA3NCwicGF0aCI6Ii81OTY4NjE5LzI5ODE0NDgwMy1jZjA3ZTIzNS00MTBiLTQwNWYtOWYyNy0yZjlhMzVlMjgxNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDIwMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmE0NTkxOTE1MzMxMmY2NGFlYTQwMzAxOWM1MzNkNmU3ZmFjYTZkZDZiNzdiMTQ5YmFiZGM3NmM0ZjY0YTU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7BdoS1f2z6V5Ud3JIEgksN00Lcy-koB0onGA9rbdP5s"> <img alt="2024-01-19_22-39-03" width="412" src="https://private-user-images.githubusercontent.com/5968619/298144835-c1a68195-1ad4-4025-a38e-36e41deba0e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTYzNzQsIm5iZiI6MTcwNTcxNjA3NCwicGF0aCI6Ii81OTY4NjE5LzI5ODE0NDgzNS1jMWE2ODE5NS0xYWQ0LTQwMjUtYTM4ZS0zNmU0MWRlYmEwZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDIwMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM0NWQ5YWE4ZGQ2MDQ0MDlkMjExYWQwYTgyM2JlYjZlNmI4Yzg2NWUwZWQxN2U5ZDFmNDg3YzZjMzM1MDUyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VOLs4whT-GSyiTWNnri2l8DziQb_ybFh4TCgWt0E_Dg">

I'll check it, thank you
